name: test
on: [push]
jobs:
  test-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v2
        with:
          go-version: "1.15"
